name: github_flutter_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity: ^3.0.6
  get_it: ^7.2.0
  shared_preferences: ^2.0.6

  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  path: ^1.8.0

  dio: ^4.0.0
  provider: ^5.0.0
  google_fonts: ^2.1.0
  another_flushbar: ^1.10.25
  local_auth: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^1.0.2
  build_runner: ^2.0.6

flutter:
  uses-material-design: true